title:  nodes
tagline:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

 # google-ID: 'UA-80213386-1'

menu:
- {name: 'home', url: '//ohheybrian.com'}
- {name: 'privacy', url: '//ohheybrian.com/privacy'}
- {name: 'DocuTube', path: 'pages', url: 'docutube.html'}
- {name: 'Doc Emailer', path: 'pages', url: 'doc-emailer.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/bennettscience'}
- {icon: 'twitter', link: 'https://twitter.com/bennettscience'}
- {icon: 'envelope', link: 'mailto:brian@ohheybrian.com'}
- {icon: 'flickr', link: 'https://flickr.com/photos/bennettscience'}
- {icon: 'rss-square', link: '/rss-feed.xml'}
